services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/repo/airflow/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - PYTHONPATH=/opt/airflow/repo
      - S3_ENDPOINT_URL=http://host.docker.internal:4566
      - QDRANT_URL=http://host.docker.internal:6333
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - RAW_BUCKET=raw
      - STAGING_BUCKET=staging
      - CURATED_BUCKET=curated
      - FINANCIAL_SOURCE_DIR=/opt/airflow/repo/prof/data_demo
      - FINANCIAL_CURATED_LIMIT=100
    volumes:
      - ..:/opt/airflow/repo
      - airflow_home:/opt/airflow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: standalone

volumes:
  airflow_home:
